# Generated by Django 3.2.6 on 2021-08-05 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=50)),
                ('mileage_in_km', models.IntegerField()),
                ('chassis_no', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('vehicle_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='app.vehicle_model')),
            ],
        ),
    ]
